import { Simulation } from '../src/sim/sim.js';
const sim = new Simulation(process.argv[2] || 'aurorae', { population: 12 });
const N = Number(process.argv[3] || 20000);
const t0 = Date.now();
for (let i = 0; i < N; i++) sim.step();
const ms = Date.now() - t0;
const r = sim.report();
console.log(`${N} ticks in ${ms}ms (${(N/ms*1000).toFixed(0)} ticks/s)`);
console.log('--- narrative ---');
r.summary.forEach(l => console.log(' ', l));
console.log('pop', r.totals.population, 'ever', r.totals.everLived, 'births', r.totals.births, 'deaths', r.totals.deaths);
console.log('concepts', r.totals.concepts, 'inventions', r.totals.inventions, 'attempts', r.totals.attempts, 'structures', r.totals.structures);
console.log('trades', r.totals.trades, 'conflicts', r.totals.conflicts, 'thefts', r.totals.thefts, 'gifts', r.totals.gifts, 'rituals', r.totals.rituals, 'art', r.totals.artworks, 'lessons', r.totals.lessons, 'laws', r.totals.laws);
console.log('eras', r.eras.map(e=>e.name).join(' | '));
console.log('bestFor', r.knowledge.bestFor.slice(0,8).map(b=>`${b.fn}:${b.word}(${b.score})`).join(', '));
console.log('roles', r.society.roles.map(x=>x.role+':'+x.n).join(', '));
console.log('causes', r.causes);
console.log('lost', r.knowledge.lostKnowledge.map(l=>l.word).join(','));
console.log('inventions tail', r.knowledge.newInventions.slice(0,6).map(i=>`${i.word}<${i.process}:${i.parents.join('+')}>=${i.fn}`).join(' | '));
console.log('demography', r.demography);
console.log('prices', r.economy.prices.slice(0,6));
console.log('sample landmarks:'); r.landmarks.slice(0,10).forEach(l=>console.log('  d'+l.day, l.text));
